#!/usr/bin/env just --justfile

# clean build directory
clean:
    @[ -d "./bin" ] && rm -r ./bin && echo "bin directory cleaned" || true

# build and compress bineary
upx: build
    upx --best --lzma bin/migration

# clean and build
build: clean
    go build -o ./bin/migration -ldflags="-s -w" .

# update go module
update:
  go get -u
  go mod tidy -v